// <auto-generated />
namespace MakeComputerShop.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addmotherboardprocessorramandproducentmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmotherboardprocessorramandproducentmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201704212035566_add motherboard, processor, ram and producent models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
