// <auto-generated />
namespace MakeComputerShop.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifycomputerandusermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifycomputerandusermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201705221903198_modify computer and user model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
