// <auto-generated />
namespace MakeComputerShop.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeusermodelagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeusermodelagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201705251738351_change user model again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
